// Default cards bundled with every fresh session.
//
// Empty for now -- a real deck (~30 generated cards) lands in a later
// step, either by importing a JSON pre-generated by the sibling
// `russian-loto` CLI or by porting the generator. Sessions can also
// supply a custom deck at creation time, bypassing this default.

export const DEFAULT_CARDS: unknown[] = [];
